BASE_URL = 'https://b2c.passport.rt.ru'

mail = 'testrtsf@yopmail.com'
login = 'Testrts'
password = 'Testrtsf1'
unknown_password = 'test'
x_password = '<script>alert(123)</script>'
unknown_mail = 'test@test.ru'
unknown_phone = '+791111111111'
unknown_ls = '123456789012'
unknown_login = 'test'
x_login = '<script>alert(666)</script>'